"""The networking layer for Media over QUIC.

Real-time pub/sub with built-in caching, fan-out, and prioritization.
"""

from moq_ffi import MoqError as Error

# A submodule, not in __all__: a star import would shadow the stdlib `json`.
from . import json as json
from .client import Client, connect
from .errors import is_auth, is_shutdown, protocol_error
from .log import log_level
from .origin import (
    Announce,
    AnnounceConsumer,
    AnnouncedBroadcast,
    AnnounceEvent,
    AnnounceEventEnd,
    AnnounceEventStart,
    AnnounceEventUpdate,
    BroadcastRequest,
    OriginConsumer,
    OriginDynamic,
    OriginProducer,
)
from .publish import (
    AudioProducer,
    BroadcastDynamic,
    BroadcastProducer,
    GroupDemand,
    GroupProducer,
    GroupRequest,
    TrackDemand,
    TrackDynamic,
    TrackProducer,
    TrackRequest,
    VideoProducer,
)
from .server import Request, Server, Transport
from .session import Bandwidth, Reservation, Session
from .subscribe import (
    AudioConsumer,
    BroadcastConsumer,
    GroupConsumer,
    TrackConsumer,
    VideoConsumer,
)
from .types import (
    AudioCodec,
    AudioDecoderOutput,
    AudioEncoderInput,
    AudioEncoderOutput,
    AudioFrame,
    AudioSampleFormat,
    Backoff,
    ConnectionStats,
    ConnectionStatus,
    Datagram,
    ErrorScope,
    FetchGroupOptions,
    Frame,
    ProtocolError,
    ProtocolKind,
    Route,
    Subscription,
    TrackInfo,
    VideoCodec,
    VideoDecodedFrame,
    VideoDecoderOutput,
    VideoEncoderInput,
    VideoEncoderKind,
    VideoEncoderOutput,
    VideoFrame,
    VideoPixelFormat,
)

__all__ = [
    "Announce",
    "AnnounceConsumer",
    "AnnouncedBroadcast",
    "AnnounceEvent",
    "AnnounceEventEnd",
    "AnnounceEventStart",
    "AnnounceEventUpdate",
    "AudioCodec",
    "AudioConsumer",
    "AudioDecoderOutput",
    "AudioEncoderInput",
    "AudioEncoderOutput",
    "AudioSampleFormat",
    "AudioFrame",
    "AudioProducer",
    "Backoff",
    "Bandwidth",
    "BroadcastConsumer",
    "BroadcastDynamic",
    "BroadcastProducer",
    "BroadcastRequest",
    "Client",
    "ConnectionStats",
    "ConnectionStatus",
    "Datagram",
    "Error",
    "ErrorScope",
    "Frame",
    "ProtocolError",
    "ProtocolKind",
    "FetchGroupOptions",
    "GroupConsumer",
    "GroupDemand",
    "GroupRequest",
    "GroupProducer",
    "OriginConsumer",
    "OriginDynamic",
    "OriginProducer",
    "Request",
    "Reservation",
    "Route",
    "Server",
    "Session",
    "Subscription",
    "TrackConsumer",
    "TrackDemand",
    "TrackDynamic",
    "TrackInfo",
    "TrackProducer",
    "TrackRequest",
    "Transport",
    "VideoCodec",
    "VideoEncoderInput",
    "VideoEncoderKind",
    "VideoEncoderOutput",
    "VideoFrame",
    "VideoConsumer",
    "VideoDecodedFrame",
    "VideoDecoderOutput",
    "VideoPixelFormat",
    "VideoProducer",
    "connect",
    "is_auth",
    "is_shutdown",
    "log_level",
    "protocol_error",
]

from . import media as media
